name: Create and publish a Docker image

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-image-on-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: downcase registry
        run: |
          echo "REPO=${REGISTRY,,}" >>${GITHUB_ENV}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: | 
            docker stop portfolio -t 3
            docker rm portfolio
            docker run --name portfolio -p 63000:3000 ${{ env.REPO }}/${{ env.IMAGE_NAME }}
